library ( rsample  )
library ( corrplot )
library ( ggplot2  )
library ( doMC     )
library ( caret    )

cat ( '\n' ) ; print ( 'new option : core ? 4' )

registerDoMC ( cores = 4 )

# -----------------------------------------------------

cat ( '\n' ) ; print ( 'Import CSV' )

mydata <- read.csv ( "Attrition.csv" )

# -----------------------------------------------------

cat ( '\n' ) ; print ( 'erase/cleaning' )

mydata $ EmployeeNumber = mydata $ Over18 = mydata $ EmployeeCount = mydata $ StandardHours = NULL

# -----------------------------------------------------

cat ( '\n' ) ; print ( 'new option : cross validation ? 10' )

set.seed ( 10000 )

fitControl = trainControl ( method = "repeatedcv" , number = 10 , repeats = 10 )

# -----------------------------------------------------

cat ( '\n' ) ; print ( 'see aviable columns' )

count = 0

for ( name in names ( mydata ) ) {

     if ( all ( is.na ( mydata [ name ] ) ) ) next
     
     print ( name ) ; count <- count + 1
}

print ( paste ( 'count:' , count ) )

# -----------------------------------------------------

cat ( '\n' ) ; print ( 'starting training knn' )

length = 20

caretmodel = train ( Attrition ~ . , data = mydata , trControl = fitControl , method = "knn" , tuneLength = length )

# tuneLength: An integer denoting the amount of granularity in the tuning
#             parameter grid. By default, this argument is the number of
#             levels for each tuning parameters that should be generated by
#           ‘ train ’. If ‘trainControl’ has the option ‘search =
#           " random "’, this is the maximum number of tuning parameter
#             combinations that will be generated by the random search.
#           ( NOTE: If given, this argument must be named. )

# tuneLength --> parameters -> max parameters ( in loop for test the better )
# sudo lscpu | grep 'CPU(s)'

str ( caretmodel )

caretmodel
caretmodel $ finalModel

# -----------------------------------------------------

print ( paste ( 'cross validation done ?' , length ) )

saveRDS ( caretmodel , "production_model.rds" )

