library ( e1071     )
library ( reshape2  )
library ( ggplot2   )
library (  car      )
library ( MASS      )
library ( mgcv      )

cat ( '\n' ) ; print ( 'glm is exactly like lm , but have family selectionable' )

lmfit1 = glm ( wages ~ age + sex + education, data = SLID , family=gaussian )

summary ( lmfit1 )

lmfit2 = lm ( wages ~ age + sex + education , data = SLID ) # previously done

anova ( lmfit1 , lmfit2 )

# -----------------------------------------------------------
# -----------------------------------------------------------

cat ( '\n' ) ; print ( 'glm have function distribution , settable like family . like +- normal distribution' )

data ( warpbreaks ) ; head ( warpbreaks )

rs1 = glm ( breaks ~ tension , data = warpbreaks , family = "poisson" )

summary ( rs1 )

print ( 'it sound like family poisson of glm is using log-linear' )

# -----------------------------------------------------------
# -----------------------------------------------------------

cat ( '\n' ) ; print ( 'glm binomial distribution family' )

head ( mtcars $ vs )

lm1 = glm ( vs ~ hp + mpg + gear , data = mtcars , family = binomial )

summary ( lm1 )

# link: a specification for the model link function.  This can be a
# name/expression, a literal character string, a length-one
# character vector, or an object of class ‘"link-glm"’ (such as
# generated by ‘make.link’) provided it is not specified _via_
# one of the standard names given next.

# The ‘gaussian’ family accepts the links (as names)
# ‘identity’, ‘log’ and ‘inverse’; the ‘binomial’ family the
# links ‘logit’, ‘probit’, ‘cauchit’, (corresponding to
# logistic, normal and Cauchy CDFs respectively) ‘log’ and
# ‘cloglog’ (complementary log-log); the ‘Gamma’ family the
# links ‘inverse’, ‘identity’ and ‘log’; the ‘poisson’ family
# the links ‘log’, ‘identity’, and ‘sqrt’; and the
# ‘inverse.gaussian’ family the links ‘1/mu^2’, ‘inverse’,
# ‘identity’ and ‘log’.

print ( 'link: a specification for the model link function == divergence' )

# -----------------------------------------------------------

cat ( '\n' ) ; print ( 'Automation family and link with Generalized additive model GAM' )

attach ( Boston )

str ( Boston )

fit = gam ( dis ~ s ( nox ) )

summary ( fit )

# The bam package is very similar to gam , but uses less memory and
# is relatively more efficient. Please use the help function for more information on this
# model: ? bam

plot ( nox , dis )

x = seq ( 0 , 1 , length = 500 )
y = predict ( fit , data.frame ( nox = x ) )
lines ( x , y , col = "red" , lwd = 2 )

plot ( fit )

# -----------------------------------------------------------

fit2 = gam ( medv ~ crim + zn + crim : zn , data = Boston )

vis.gam ( fit2 )

# -----------------------------------------------------------

cat ( '\n' ) ; print ( 'GAM check:' )

gam.check ( fit )

print ( 'for me GAM is not useful, it is like a black box' )



